# Generated by Django 5.0.1 on 2024-02-08 14:33

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='src',
            field=models.ImageField(blank=True, default='pics/avatar.jpg', null=True, upload_to=profiles.models.profile_avatar_directory_path, verbose_name='avatar'),
        ),
    ]
