# Generated by Django 5.0.1 on 2024-02-11 11:24

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_alt_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='src',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_avatar_directory_path, verbose_name='avatar'),
        ),
    ]
