# Generated by Django 5.0.1 on 2024-03-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('month', models.CharField(blank=True, default='', max_length=2)),
                ('year', models.CharField(blank=True, default='', max_length=4)),
                ('code', models.CharField(blank=True, default='', max_length=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order')),
            ],
        ),
    ]
