# Generated by Django 5.0.1 on 2024-02-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(default=123456789, max_length=1024),
            preserve_default=False,
        ),
    ]
