# Generated by Django 5.0.1 on 2024-03-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standart', models.DecimalField(decimal_places=2, max_digits=5)),
                ('express', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
