# Generated by Django 5.0.1 on 2024-03-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_deliverycost_datefrom_deliverycost_dateto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycost',
            name='dateTo',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='deliverycost',
            name='express',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliverycost',
            name='minCostForFreeDelivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliverycost',
            name='standart',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
