# Generated by Django 5.0.1 on 2024-02-17 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderinfo_customer_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='deliveryType',
            field=models.CharField(choices=[('free', 'Free'), ('toll', 'Paid')], default='free', max_length=4),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='fullName',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
