# Generated by Django 5.0.1 on 2024-03-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_deliverycost_dateto_alter_deliverycost_express_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycost',
            old_name='standart',
            new_name='ordinary',
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(choices=[('ordinary', 'Ordinary'), ('express', 'Express')], default='ordinary', max_length=10),
        ),
    ]
