# Generated by Django 5.0.1 on 2024-02-17 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderinfo_deliverytype_orderinfo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(choices=[('free', 'Free'), ('toll', 'Paid')], default='free', max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fullName',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='paymentType',
            field=models.CharField(choices=[('card', 'Card'), ('random account', 'Random Account')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
