# Generated by Django 5.0.1 on 2024-02-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_address_order_deliverytype_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fullName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
