# Generated by Django 5.0.1 on 2024-02-21 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_email_alter_order_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totalCost',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.order'),
        ),
    ]
