# Generated by Django 5.0.1 on 2024-02-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_totalcost_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(choices=[('free', 'Free'), ('express', 'Paid')], default='free', max_length=7),
        ),
    ]
