# Generated by Django 5.0.1 on 2024-02-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_deliverytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.CharField(choices=[('online', 'Card'), ('random account', 'Random Account')], default='online', max_length=20),
        ),
    ]
