# Generated by Django 5.0.1 on 2024-02-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(choices=[('ordinary', 'Free'), ('express', 'Paid')], default='ordinary', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.CharField(choices=[('online', 'Card'), ('someone', 'Random Account')], default='online', max_length=20),
        ),
    ]
