# Generated by Django 5.0.1 on 2024-01-28 08:59

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='src',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.category_image_directory_path),
        ),
    ]
