# Generated by Django 5.0.1 on 2024-02-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent', default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='catalog.category'),
            preserve_default=False,
        ),
    ]
