# Generated by Django 5.0.1 on 2024-01-28 18:50

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_alt_category_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='src',
            field=models.ImageField(default='pics/daisy.jpeg', upload_to=catalog.models.category_image_directory_path),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product'),
        ),
    ]
