# Generated by Django 5.0.1 on 2024-03-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specification',
            options={'ordering': ['name']},
        ),
    ]
